name: frontend-ci deploy vercel

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: install dependencies
        run: npm ci
      
      - name: build project
        run: npm run build

      - name: debug secret
        run: echo "VERCEL_TOKEN is ${VERCEL_TOKEN}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      
      - name: deploy to vercel
        run: | 
          npm install -g vercel
          vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} \
          --confirm \
          --project ${{ secrets.VERCEL_PROJECT_ID }} \